Repository etalab/transport-profil-netex-fr, pull requests merged in 2025-08, with the labels that each got.

#205 element communs - ajout des sous-modes Coach de Netex
  NeTEx/elements_communs/index.md
Labels: documentation, NeTEx

#202 Arrêts - Modifications sur les références vers les zones tarifaires
  NeTEx/arrets/index.md
Labels: Offre tarifaire

#203 Tarifs - Précision sur le libellé court de la zone tarifaire
  NeTEx/tarifs/index.md
Labels: Offre tarifaire

#209 Update README.md
  README.md
Labels: documentation

#207 Elements communs: typos et format
  NeTEx/elements_communs/index.md
Labels: documentation
