Repository etalab/transport-profil-netex-fr, pull requests merged in 2025-01, with the labels that each got.

#132 Correction de vocabulaire sur les zone tarifaires et billettiques
  NeTEx/tarifs/index.md
Labels: documentation, Offre tarifaire

#127 Correction de typos (source Ticks)
  NeTEx/tarifs/index.md
Labels: documentation, Offre tarifaire, validé en GT7

#135 MàJ du readme et archivage du contenu de l'ancien
  README.md
Labels: documentation
